a => a.number("agentId")
                    .text("firstName")
                    .text("lastName")
                    .text("contactNumber")
                    .text("email")
                    .number("commissionRate")