a => a.number("claimId")
                    .date("claimReportedDate")
                    .date("claimPaidDate")
                    .date("claimEndDate")
                    .number("claimAmount")
                    .datalist("claimStatuses", d => d.toLinkedMap(["APPROVED", "REJECTED", "PENDING"]))
                    .dropdown("status", "claimStatuses")
                    .text("description")
                    .manyToOne("policyId","policy")
                    .manyToOne("beneficiaryId","beneficiary")