a => a.number("clientId")
                    .text("firstName")
                    .text("lastName")
                    .date("dateOfBirth")
                    .text("gender")
                    .text("email")
                    .text("address")
                    .text("companyName")
                    .text("companyLegalName")
                    .text("taxNumber")
                    .text("contactPerson")
                    .text("contactAddress")
                    .text("billingAddress")
                    .text("contactNumber")
                    .datalist("clientStatuses", d => d.toLinkedMap(["Active", "Prospect", "Both"]))
                    .dropdown("clientStatus", "clientStatuses")
                    .datalist("clientTypes", d => d.toLinkedMap(["BusinessClient", "ConsumerClient", "Other"]))
                    .dropdown("clientType", "clientTypes")