a => a.number("paymentId")
                    .number("amount")
                    .date("paymentDueDate")
                    .date("paymentDate")
                    .datalist("paymentMethods", d => d.toLinkedMap(["CREDIT_CARD","BANK_TRANSFER","CASH","CHEQUE"]))
                    .dropdown("paymentMethod", "paymentMethods")
                    .datalist("paymentStatuses", d => d.toLinkedMap(["PAID", "UNPAID", "PENDING"]))
                    .dropdown("paymentStatus", "paymentStatuses")
                    .manyToOne("policyId","policy")