a => a.number("policyId")
                    .text("policyName")
                    .datalist("policyTypes", d => d.toLinkedMap(["TERM", "WHOLE_LIFE", "UNIVERSAL", "ENDOWMENT", "CAR", "PROPERTY", "GENERAL LIABILITY", "COMMERCIAL CAR", "FLEET", "COMMERCIAL PROPERTY", "CYBER RISK", "PRODUCT LIABILITY", "TRAVEL"]))
                    .dropdown("policyType", "policyTypes")
                    .text("policyDescription")
                    .date("startDate")
                    .date("endDate")
                    .date("coverageStartDate")
                    .date("coverageEndDate")
                    .number("premium")
                    .datalist("premiumPaymentTypes", d => d.toLinkedMap(["MONTHLY", "QUARTERLY", "ANNUALLY", "SEMI_ANNUALLY", "SINGLE"]))
                    .dropdown("premiumPaymentType", "premiumPaymentTypes")
                    .datalist("policyStatuses", d => d.toLinkedMap(["Active", "Expired", "Cancelled"]))
                    .dropdown("status", "policyStatuses")
                    .manyToOne("customerId","customer")
                    .manyToOne("agentId","agent")
                    .manyToOne("coverageId","coverage")
                    .manyToOne("beneficiaryId","beneficiary")