a => a.number("propertyId")
                    .text("address")
                    .text("city")
                    .text("state")
                    .text("zipCode")
                    .number("propertyValue")
                    .datalist("propertyTypes", d => d.toLinkedMap(["RESIDENTIAL", "COMMERCIAL", "INDUSTRIAL", "AGRICULTURAL", "MIXED_USE"]))
                    .dropdown("propertyType", "propertyTypes")
                    .manyToOne("coverageId","coverage")