spring.datasource.url=jdbc:postgresql://localhost:5432/boards
logo.image.href.global=/html/dashboard
global.initialization.scripts.commaseparated=/db/init.sql,/boards-init.sql
spring.messages.basename=messages,messages-attribute,messages-integration,messages-boards
