spring.datasource.url=jdbc:postgresql://localhost:5432/asset-management
logo.image.href.global=/html/dashboard
global.initialization.scripts.commaseparated=/db/init.sql,/db/asset-management-init.sql
page.after.auth=/html/webEndpoint/asset-management
page.after.auth.for.global.admin=/html/webEndpoint/asset-management
